name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: [self-hosted,linux]
    permissions:
      issues: write
      pull-requests: write
    steps:
      - run: echo "Hello world"

